// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALcIHF7d8UqyXGI6PqlTHHRhxj7nxYUJk',
    appId: '1:738801390261:web:41ab05eb371ff372bce4fc',
    messagingSenderId: '738801390261',
    projectId: 'km-moters-ecosystem',
    authDomain: 'km-moters-ecosystem.firebaseapp.com',
    storageBucket: 'km-moters-ecosystem.firebasestorage.app',
    measurementId: 'G-E921Y5HG3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeIdix80NBgAVmgbsgvV64P8e6XIgQS3Q',
    appId: '1:738801390261:android:b8a0d0281b47c012bce4fc',
    messagingSenderId: '738801390261',
    projectId: 'km-moters-ecosystem',
    storageBucket: 'km-moters-ecosystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNt2XFHe8N9cn5gOR0IctmhefT56-SFo',
    appId: '1:738801390261:ios:64df78a37b5361d0bce4fc',
    messagingSenderId: '738801390261',
    projectId: 'km-moters-ecosystem',
    storageBucket: 'km-moters-ecosystem.firebasestorage.app',
    iosBundleId: 'com.example.kmDrive',
  );
}
